import { CardTemplate } from './types';

export const CARD_TEMPLATES: CardTemplate[] = [
    // ========== TIER 1 (1g) ==========
    {
        id: 'c1',
        name: 'Vanguard',
        tier: 1,
        hp: 600,
        ad: 50,
        ap: 0,
        manaMax: 100,
        as: 0.6,
        range: 1,
        traits: ['Protector', 'Steel'],
        abilityName: 'Iron Shield',
        abilityDescription: 'Gains 200 shield for 4 seconds.'
    },
    {
        id: 'c2',
        name: 'Stinger',
        tier: 1,
        hp: 450,
        ad: 65,
        ap: 0,
        manaMax: 50,
        as: 0.8,
        range: 1,
        traits: ['Assassin', 'Shadow'],
        abilityName: 'Toxic Strike',
        abilityDescription: 'Next attack deals 50 bonus poison damage.'
    },
    {
        id: 'c1_3',
        name: 'Ranger',
        tier: 1,
        hp: 500,
        ad: 55,
        ap: 0,
        manaMax: 60,
        as: 0.75,
        range: 3,
        traits: ['Sniper', 'Wind'],
        abilityName: 'Rapid Fire',
        abilityDescription: 'Gains 50% attack speed for 3 seconds.'
    },
    {
        id: 'c1_4',
        name: 'Scrap',
        tier: 1,
        hp: 650,
        ad: 45,
        ap: 0,
        manaMax: 80,
        as: 0.55,
        range: 1,
        traits: ['Brawler', 'Mech'],
        abilityName: 'Scrap Shield',
        abilityDescription: 'Gains 150 shield.'
    },
    {
        id: 'c1_5',
        name: 'Acolyte',
        tier: 1,
        hp: 500,
        ad: 40,
        ap: 50,
        manaMax: 70,
        as: 0.65,
        range: 2,
        traits: ['Mage', 'Mystic'],
        abilityName: 'Healing Touch',
        abilityDescription: 'Heals lowest HP ally for 200.'
    },
    {
        id: 'c1_6',
        name: 'Drone',
        tier: 1,
        hp: 480,
        ad: 60,
        ap: 0,
        manaMax: 55,
        as: 0.7,
        range: 3,
        traits: ['Cybernetic', 'Gunner'],
        abilityName: 'Double Shot',
        abilityDescription: 'Fires 2 shots at random enemies.'
    },

    // ========== TIER 2 (2g) ==========
    {
        id: 'c3',
        name: 'Oracle',
        tier: 2,
        hp: 500,
        ad: 40,
        ap: 60,
        manaMax: 80,
        as: 0.65,
        range: 3,
        traits: ['Mage', 'Mystic'],
        abilityName: 'Arcane Bolt',
        abilityDescription: 'Deals 150 magic damage to target.'
    },
    {
        id: 'c4',
        name: 'Brawler',
        tier: 2,
        hp: 800,
        ad: 55,
        ap: 0,
        manaMax: 120,
        as: 0.55,
        range: 1,
        traits: ['Brawler', 'Earth'],
        abilityName: 'Ground Slam',
        abilityDescription: 'Stuns adjacent enemies for 1.5s.'
    },
    {
        id: 'c2_3',
        name: 'Shadowblade',
        tier: 2,
        hp: 550,
        ad: 75,
        ap: 0,
        manaMax: 60,
        as: 0.85,
        range: 1,
        traits: ['Assassin', 'Void'],
        abilityName: 'Backstab',
        abilityDescription: 'Teleports behind enemy, deals 200 damage.'
    },
    {
        id: 'c2_4',
        name: 'Sentinel',
        tier: 2,
        hp: 850,
        ad: 50,
        ap: 0,
        manaMax: 100,
        as: 0.5,
        range: 1,
        traits: ['Protector', 'Celestial'],
        abilityName: 'Taunt',
        abilityDescription: 'Forces nearby enemies to attack this unit.'
    },
    {
        id: 'c2_5',
        name: 'Blaster',
        tier: 2,
        hp: 600,
        ad: 70,
        ap: 0,
        manaMax: 70,
        as: 0.7,
        range: 3,
        traits: ['Gunner', 'Cybernetic'],
        abilityName: 'Missile Barrage',
        abilityDescription: 'Fires 3 missiles at random enemies.'
    },
    {
        id: 'c2_6',
        name: 'Nomad',
        tier: 2,
        hp: 650,
        ad: 80,
        ap: 0,
        manaMax: 65,
        as: 0.8,
        range: 1,
        traits: ['Blademaster', 'Wind'],
        abilityName: 'Dash Strike',
        abilityDescription: 'Dashes to enemy, deals 180 damage.'
    },

    // ========== TIER 3 (3g) ==========
    {
        id: 'c5',
        name: 'Sniper',
        tier: 3,
        hp: 550,
        ad: 80,
        ap: 0,
        manaMax: 60,
        as: 0.75,
        range: 4,
        traits: ['Sniper', 'Wind'],
        abilityName: 'Piercing Shot',
        abilityDescription: 'Next attack deals damage to all enemies in a line.'
    },
    {
        id: 'c3_2',
        name: 'Void Terror',
        tier: 3,
        hp: 900,
        ad: 90,
        ap: 0,
        manaMax: 90,
        as: 0.6,
        range: 1,
        traits: ['Brawler', 'Void'],
        abilityName: 'Void Bite',
        abilityDescription: 'Deals 250 true damage (ignores armor).'
    },
    {
        id: 'c3_3',
        name: 'Flux Mage',
        tier: 3,
        hp: 600,
        ad: 50,
        ap: 80,
        manaMax: 75,
        as: 0.7,
        range: 3,
        traits: ['Mage', 'Chrono'],
        abilityName: 'Time Freeze',
        abilityDescription: 'Stuns target for 2 seconds.'
    },
    {
        id: 'c3_4',
        name: 'Warlord',
        tier: 3,
        hp: 750,
        ad: 95,
        ap: 0,
        manaMax: 80,
        as: 0.65,
        range: 1,
        traits: ['Blademaster', 'Steel'],
        abilityName: 'Whirlwind',
        abilityDescription: 'Spins, dealing 150 damage to adjacent enemies.'
    },
    {
        id: 'c3_5',
        name: 'Nanomancer',
        tier: 3,
        hp: 650,
        ad: 60,
        ap: 70,
        manaMax: 85,
        as: 0.68,
        range: 2,
        traits: ['Cybernetic', 'Mystic'],
        abilityName: 'Life Drain',
        abilityDescription: 'Drains 200 HP from enemy, heals self.'
    },
    {
        id: 'c3_6',
        name: 'Skyguardian',
        tier: 3,
        hp: 800,
        ad: 65,
        ap: 0,
        manaMax: 100,
        as: 0.6,
        range: 1,
        traits: ['Protector', 'Celestial'],
        abilityName: 'Divine Shield',
        abilityDescription: 'Becomes immune to damage for 2 seconds.'
    },

    // ========== TIER 4 (4g) ==========
    {
        id: 'c4_1',
        name: 'Titan',
        tier: 4,
        hp: 1200,
        ad: 100,
        ap: 0,
        manaMax: 110,
        as: 0.5,
        range: 1,
        traits: ['Brawler', 'Earth'],
        abilityName: 'Earthquake',
        abilityDescription: 'Knocks back all nearby enemies, deals 200 damage.'
    },
    {
        id: 'c4_2',
        name: 'Arcane Dragon',
        tier: 4,
        hp: 850,
        ad: 70,
        ap: 120,
        manaMax: 100,
        as: 0.6,
        range: 3,
        traits: ['Mage', 'Chrono'],
        abilityName: 'Dragon Breath',
        abilityDescription: 'Breathes fire in a cone, dealing 300 magic damage over time.'
    },
    {
        id: 'c4_3',
        name: 'Phantom',
        tier: 4,
        hp: 700,
        ad: 120,
        ap: 0,
        manaMax: 70,
        as: 0.9,
        range: 1,
        traits: ['Assassin', 'Shadow'],
        abilityName: 'Execute',
        abilityDescription: 'Instantly kills enemies below 30% HP.'
    },
    {
        id: 'c4_4',
        name: 'Stormcaller',
        tier: 4,
        hp: 750,
        ad: 80,
        ap: 100,
        manaMax: 95,
        as: 0.65,
        range: 3,
        traits: ['Mystic', 'Wind'],
        abilityName: 'Tornado',
        abilityDescription: 'Summons tornado, stunning all enemies for 1.5s.'
    },
    {
        id: 'c4_5',
        name: 'Mech-Pilot',
        tier: 4,
        hp: 900,
        ad: 110,
        ap: 0,
        manaMax: 120,
        as: 0.55,
        range: 2,
        traits: ['Mech', 'Gunner'],
        abilityName: 'Mech Transform',
        abilityDescription: 'Transforms, gaining 500 HP and 50 AD.'
    },
    {
        id: 'c4_6',
        name: 'Highblade',
        tier: 4,
        hp: 800,
        ad: 115,
        ap: 0,
        manaMax: 85,
        as: 0.75,
        range: 1,
        traits: ['Blademaster', 'Celestial'],
        abilityName: 'Shockwave',
        abilityDescription: 'Sends energy wave, dealing 250 damage in a line.'
    },

    // ========== TIER 5 (5g - Legendary) ==========
    {
        id: 'c5_1',
        name: 'The Core',
        tier: 5,
        hp: 1000,
        ad: 90,
        ap: 150,
        manaMax: 150,
        as: 0.6,
        range: 4,
        traits: ['Cybernetic', 'Steel'],
        abilityName: 'Orbital Laser',
        abilityDescription: 'Fires laser from orbit, dealing 400 damage to all enemies.'
    },
    {
        id: 'c5_2',
        name: 'Void Mother',
        tier: 5,
        hp: 1100,
        ad: 80,
        ap: 140,
        manaMax: 140,
        as: 0.55,
        range: 2,
        traits: ['Void', 'Mage'],
        abilityName: 'Summon Voidlings',
        abilityDescription: 'Summons 3 mini-voids to fight.'
    },
    {
        id: 'c5_3',
        name: 'Time Keeper',
        tier: 5,
        hp: 950,
        ad: 70,
        ap: 160,
        manaMax: 160,
        as: 0.65,
        range: 3,
        traits: ['Chrono', 'Mystic'],
        abilityName: 'Time Stop',
        abilityDescription: 'Freezes all enemies for 3 seconds.'
    },
    {
        id: 'c5_4',
        name: 'Starforger',
        tier: 5,
        hp: 1300,
        ad: 100,
        ap: 0,
        manaMax: 130,
        as: 0.5,
        range: 1,
        traits: ['Celestial', 'Protector'],
        abilityName: 'Cosmic Shield',
        abilityDescription: 'Grants 500 shield to all allies.'
    },
    {
        id: 'c5_5',
        name: 'Deathwhisper',
        tier: 5,
        hp: 800,
        ad: 150,
        ap: 0,
        manaMax: 100,
        as: 1.0,
        range: 4,
        traits: ['Assassin', 'Shadow', 'Sniper'],
        abilityName: 'Assassination',
        abilityDescription: 'Instantly kills one non-boss enemy.'
    },
    {
        id: 'c5_6',
        name: 'Omega',
        tier: 5,
        hp: 1400,
        ad: 120,
        ap: 0,
        manaMax: 200,
        as: 0.45,
        range: 1,
        traits: ['Mech', 'Brawler'],
        abilityName: 'Self-Destruct',
        abilityDescription: 'On death, explodes dealing 600 damage to all nearby enemies.'
    }
];

export const MONSTER_TEMPLATES: CardTemplate[] = [
    { id: 'm_minion_melee', name: 'Melee Minion', tier: 1, hp: 300, ad: 40, ap: 0, manaMax: 0, as: 0.5, range: 1, traits: [], abilityName: '', abilityDescription: '' },
    { id: 'm_minion_ranged', name: 'Caster Minion', tier: 1, hp: 200, ad: 55, ap: 0, manaMax: 0, as: 0.6, range: 3, traits: [], abilityName: '', abilityDescription: '' },
    { id: 'm_krug', name: 'Krug', tier: 2, hp: 1200, ad: 80, ap: 0, manaMax: 0, as: 0.4, range: 1, traits: ['Earth'], abilityName: 'Stone Skin', abilityDescription: 'Reduces incoming damage.' },
    { id: 'm_wolf', name: 'Murk Wolf', tier: 2, hp: 600, ad: 100, ap: 0, manaMax: 0, as: 0.8, range: 1, traits: ['Assassin'], abilityName: 'Bite', abilityDescription: 'Critical strike chance.' },
    { id: 'm_raptor', name: 'Razorbeak', tier: 3, hp: 400, ad: 120, ap: 0, manaMax: 0, as: 1.0, range: 1, traits: [], abilityName: '', abilityDescription: '' },
];

export const WAVES: Record<number, string[]> = {
    1: ['m_minion_melee', 'm_minion_melee'],
    2: ['m_minion_melee', 'm_minion_ranged', 'm_minion_melee'],
    3: ['m_minion_melee', 'm_minion_ranged', 'm_minion_ranged', 'm_minion_melee'],
    10: ['m_krug', 'm_krug', 'm_krug'], // Boss Wave
    15: ['m_wolf', 'm_wolf', 'm_wolf', 'm_wolf'],
    20: ['m_raptor', 'm_raptor', 'm_raptor', 'm_raptor', 'm_raptor'],
};
